// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pull-request-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

type PullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PullRequestRepository) EXPECT() *PullRequestRepository_Expecter {
	return &PullRequestRepository_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function with given fields: ctx, pr
func (_m *PullRequestRepository) CreatePR(ctx context.Context, pr *models.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestRepository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type PullRequestRepository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequest
func (_e *PullRequestRepository_Expecter) CreatePR(ctx interface{}, pr interface{}) *PullRequestRepository_CreatePR_Call {
	return &PullRequestRepository_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, pr)}
}

func (_c *PullRequestRepository_CreatePR_Call) Run(run func(ctx context.Context, pr *models.PullRequest)) *PullRequestRepository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequest))
	})
	return _c
}

func (_c *PullRequestRepository_CreatePR_Call) Return(_a0 error) *PullRequestRepository_CreatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullRequestRepository_CreatePR_Call) RunAndReturn(run func(context.Context, *models.PullRequest) error) *PullRequestRepository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPR provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) GetPR(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_GetPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPR'
type PullRequestRepository_GetPR_Call struct {
	*mock.Call
}

// GetPR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PullRequestRepository_Expecter) GetPR(ctx interface{}, prID interface{}) *PullRequestRepository_GetPR_Call {
	return &PullRequestRepository_GetPR_Call{Call: _e.mock.On("GetPR", ctx, prID)}
}

func (_c *PullRequestRepository_GetPR_Call) Run(run func(ctx context.Context, prID string)) *PullRequestRepository_GetPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_GetPR_Call) Return(_a0 *models.PullRequest, _a1 error) *PullRequestRepository_GetPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_GetPR_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *PullRequestRepository_GetPR_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) MergePR(ctx context.Context, prID string) error {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestRepository_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type PullRequestRepository_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PullRequestRepository_Expecter) MergePR(ctx interface{}, prID interface{}) *PullRequestRepository_MergePR_Call {
	return &PullRequestRepository_MergePR_Call{Call: _e.mock.On("MergePR", ctx, prID)}
}

func (_c *PullRequestRepository_MergePR_Call) Run(run func(ctx context.Context, prID string)) *PullRequestRepository_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_MergePR_Call) Return(_a0 error) *PullRequestRepository_MergePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullRequestRepository_MergePR_Call) RunAndReturn(run func(context.Context, string) error) *PullRequestRepository_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
