// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pull-request-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ReviewRepository is an autogenerated mock type for the ReviewRepository type
type ReviewRepository struct {
	mock.Mock
}

type ReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReviewRepository) EXPECT() *ReviewRepository_Expecter {
	return &ReviewRepository_Expecter{mock: &_m.Mock}
}

// AddReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *ReviewRepository) AddReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReviewRepository_AddReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReviewer'
type ReviewRepository_AddReviewer_Call struct {
	*mock.Call
}

// AddReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *ReviewRepository_Expecter) AddReviewer(ctx interface{}, prID interface{}, userID interface{}) *ReviewRepository_AddReviewer_Call {
	return &ReviewRepository_AddReviewer_Call{Call: _e.mock.On("AddReviewer", ctx, prID, userID)}
}

func (_c *ReviewRepository_AddReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *ReviewRepository_AddReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReviewRepository_AddReviewer_Call) Return(_a0 error) *ReviewRepository_AddReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReviewRepository_AddReviewer_Call) RunAndReturn(run func(context.Context, string, string) error) *ReviewRepository_AddReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRReviewers provides a mock function with given fields: ctx, prID
func (_m *ReviewRepository) GetPRReviewers(ctx context.Context, prID string) ([]string, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRReviewers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewRepository_GetPRReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRReviewers'
type ReviewRepository_GetPRReviewers_Call struct {
	*mock.Call
}

// GetPRReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *ReviewRepository_Expecter) GetPRReviewers(ctx interface{}, prID interface{}) *ReviewRepository_GetPRReviewers_Call {
	return &ReviewRepository_GetPRReviewers_Call{Call: _e.mock.On("GetPRReviewers", ctx, prID)}
}

func (_c *ReviewRepository_GetPRReviewers_Call) Run(run func(ctx context.Context, prID string)) *ReviewRepository_GetPRReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReviewRepository_GetPRReviewers_Call) Return(_a0 []string, _a1 error) *ReviewRepository_GetPRReviewers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReviewRepository_GetPRReviewers_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *ReviewRepository_GetPRReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRsByReviewer provides a mock function with given fields: ctx, userID
func (_m *ReviewRepository) GetPRsByReviewer(ctx context.Context, userID string) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsByReviewer")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewRepository_GetPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsByReviewer'
type ReviewRepository_GetPRsByReviewer_Call struct {
	*mock.Call
}

// GetPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ReviewRepository_Expecter) GetPRsByReviewer(ctx interface{}, userID interface{}) *ReviewRepository_GetPRsByReviewer_Call {
	return &ReviewRepository_GetPRsByReviewer_Call{Call: _e.mock.On("GetPRsByReviewer", ctx, userID)}
}

func (_c *ReviewRepository_GetPRsByReviewer_Call) Run(run func(ctx context.Context, userID string)) *ReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReviewRepository_GetPRsByReviewer_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *ReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReviewRepository_GetPRsByReviewer_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequestShort, error)) *ReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *ReviewRepository) RemoveReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReviewRepository_RemoveReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReviewer'
type ReviewRepository_RemoveReviewer_Call struct {
	*mock.Call
}

// RemoveReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *ReviewRepository_Expecter) RemoveReviewer(ctx interface{}, prID interface{}, userID interface{}) *ReviewRepository_RemoveReviewer_Call {
	return &ReviewRepository_RemoveReviewer_Call{Call: _e.mock.On("RemoveReviewer", ctx, prID, userID)}
}

func (_c *ReviewRepository_RemoveReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *ReviewRepository_RemoveReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReviewRepository_RemoveReviewer_Call) Return(_a0 error) *ReviewRepository_RemoveReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReviewRepository_RemoveReviewer_Call) RunAndReturn(run func(context.Context, string, string) error) *ReviewRepository_RemoveReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewReviewRepository creates a new instance of ReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewRepository {
	mock := &ReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
