// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamUsersRepository is an autogenerated mock type for the TeamUsersRepository type
type TeamUsersRepository struct {
	mock.Mock
}

type TeamUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamUsersRepository) EXPECT() *TeamUsersRepository_Expecter {
	return &TeamUsersRepository_Expecter{mock: &_m.Mock}
}

// UpsertUser provides a mock function with given fields: ctx, userID, username, teamName, isActive
func (_m *TeamUsersRepository) UpsertUser(ctx context.Context, userID string, username string, teamName string, isActive bool) error {
	ret := _m.Called(ctx, userID, username, teamName, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) error); ok {
		r0 = rf(ctx, userID, username, teamName, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamUsersRepository_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type TeamUsersRepository_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - username string
//   - teamName string
//   - isActive bool
func (_e *TeamUsersRepository_Expecter) UpsertUser(ctx interface{}, userID interface{}, username interface{}, teamName interface{}, isActive interface{}) *TeamUsersRepository_UpsertUser_Call {
	return &TeamUsersRepository_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, userID, username, teamName, isActive)}
}

func (_c *TeamUsersRepository_UpsertUser_Call) Run(run func(ctx context.Context, userID string, username string, teamName string, isActive bool)) *TeamUsersRepository_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *TeamUsersRepository_UpsertUser_Call) Return(_a0 error) *TeamUsersRepository_UpsertUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamUsersRepository_UpsertUser_Call) RunAndReturn(run func(context.Context, string, string, string, bool) error) *TeamUsersRepository_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamUsersRepository creates a new instance of TeamUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamUsersRepository {
	mock := &TeamUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
