// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pull-request-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TeamsRepository is an autogenerated mock type for the TeamsRepository type
type TeamsRepository struct {
	mock.Mock
}

type TeamsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsRepository) EXPECT() *TeamsRepository_Expecter {
	return &TeamsRepository_Expecter{mock: &_m.Mock}
}

// GetActiveTeamMembers provides a mock function with given fields: ctx, teamName, excludeUserID
func (_m *TeamsRepository) GetActiveTeamMembers(ctx context.Context, teamName string, excludeUserID string) ([]string, error) {
	ret := _m.Called(ctx, teamName, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTeamMembers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, teamName, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, teamName, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamName, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsRepository_GetActiveTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTeamMembers'
type TeamsRepository_GetActiveTeamMembers_Call struct {
	*mock.Call
}

// GetActiveTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeUserID string
func (_e *TeamsRepository_Expecter) GetActiveTeamMembers(ctx interface{}, teamName interface{}, excludeUserID interface{}) *TeamsRepository_GetActiveTeamMembers_Call {
	return &TeamsRepository_GetActiveTeamMembers_Call{Call: _e.mock.On("GetActiveTeamMembers", ctx, teamName, excludeUserID)}
}

func (_c *TeamsRepository_GetActiveTeamMembers_Call) Run(run func(ctx context.Context, teamName string, excludeUserID string)) *TeamsRepository_GetActiveTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TeamsRepository_GetActiveTeamMembers_Call) Return(_a0 []string, _a1 error) *TeamsRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsRepository_GetActiveTeamMembers_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *TeamsRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *TeamsRepository) GetTeam(ctx context.Context, teamName string) (*models.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsRepository_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type TeamsRepository_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *TeamsRepository_Expecter) GetTeam(ctx interface{}, teamName interface{}) *TeamsRepository_GetTeam_Call {
	return &TeamsRepository_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *TeamsRepository_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *TeamsRepository_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamsRepository_GetTeam_Call) Return(_a0 *models.Team, _a1 error) *TeamsRepository_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsRepository_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *TeamsRepository_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeam provides a mock function with given fields: ctx, userID
func (_m *TeamsRepository) GetUserTeam(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeam")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsRepository_GetUserTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeam'
type TeamsRepository_GetUserTeam_Call struct {
	*mock.Call
}

// GetUserTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TeamsRepository_Expecter) GetUserTeam(ctx interface{}, userID interface{}) *TeamsRepository_GetUserTeam_Call {
	return &TeamsRepository_GetUserTeam_Call{Call: _e.mock.On("GetUserTeam", ctx, userID)}
}

func (_c *TeamsRepository_GetUserTeam_Call) Run(run func(ctx context.Context, userID string)) *TeamsRepository_GetUserTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamsRepository_GetUserTeam_Call) Return(_a0 string, _a1 error) *TeamsRepository_GetUserTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsRepository_GetUserTeam_Call) RunAndReturn(run func(context.Context, string) (string, error)) *TeamsRepository_GetUserTeam_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTeam provides a mock function with given fields: ctx, teamName
func (_m *TeamsRepository) InsertTeam(ctx context.Context, teamName string) error {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for InsertTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamsRepository_InsertTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTeam'
type TeamsRepository_InsertTeam_Call struct {
	*mock.Call
}

// InsertTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *TeamsRepository_Expecter) InsertTeam(ctx interface{}, teamName interface{}) *TeamsRepository_InsertTeam_Call {
	return &TeamsRepository_InsertTeam_Call{Call: _e.mock.On("InsertTeam", ctx, teamName)}
}

func (_c *TeamsRepository_InsertTeam_Call) Run(run func(ctx context.Context, teamName string)) *TeamsRepository_InsertTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamsRepository_InsertTeam_Call) Return(_a0 error) *TeamsRepository_InsertTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamsRepository_InsertTeam_Call) RunAndReturn(run func(context.Context, string) error) *TeamsRepository_InsertTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamsRepository creates a new instance of TeamsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsRepository {
	mock := &TeamsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
