// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamInfoRepository is an autogenerated mock type for the TeamInfoRepository type
type TeamInfoRepository struct {
	mock.Mock
}

type TeamInfoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamInfoRepository) EXPECT() *TeamInfoRepository_Expecter {
	return &TeamInfoRepository_Expecter{mock: &_m.Mock}
}

// GetActiveTeamMembers provides a mock function with given fields: ctx, teamName, excludeUserID
func (_m *TeamInfoRepository) GetActiveTeamMembers(ctx context.Context, teamName string, excludeUserID string) ([]string, error) {
	ret := _m.Called(ctx, teamName, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTeamMembers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, teamName, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, teamName, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamName, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamInfoRepository_GetActiveTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTeamMembers'
type TeamInfoRepository_GetActiveTeamMembers_Call struct {
	*mock.Call
}

// GetActiveTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeUserID string
func (_e *TeamInfoRepository_Expecter) GetActiveTeamMembers(ctx interface{}, teamName interface{}, excludeUserID interface{}) *TeamInfoRepository_GetActiveTeamMembers_Call {
	return &TeamInfoRepository_GetActiveTeamMembers_Call{Call: _e.mock.On("GetActiveTeamMembers", ctx, teamName, excludeUserID)}
}

func (_c *TeamInfoRepository_GetActiveTeamMembers_Call) Run(run func(ctx context.Context, teamName string, excludeUserID string)) *TeamInfoRepository_GetActiveTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TeamInfoRepository_GetActiveTeamMembers_Call) Return(_a0 []string, _a1 error) *TeamInfoRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamInfoRepository_GetActiveTeamMembers_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *TeamInfoRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeam provides a mock function with given fields: ctx, userID
func (_m *TeamInfoRepository) GetUserTeam(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeam")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamInfoRepository_GetUserTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeam'
type TeamInfoRepository_GetUserTeam_Call struct {
	*mock.Call
}

// GetUserTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TeamInfoRepository_Expecter) GetUserTeam(ctx interface{}, userID interface{}) *TeamInfoRepository_GetUserTeam_Call {
	return &TeamInfoRepository_GetUserTeam_Call{Call: _e.mock.On("GetUserTeam", ctx, userID)}
}

func (_c *TeamInfoRepository_GetUserTeam_Call) Run(run func(ctx context.Context, userID string)) *TeamInfoRepository_GetUserTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamInfoRepository_GetUserTeam_Call) Return(_a0 string, _a1 error) *TeamInfoRepository_GetUserTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamInfoRepository_GetUserTeam_Call) RunAndReturn(run func(context.Context, string) (string, error)) *TeamInfoRepository_GetUserTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamInfoRepository creates a new instance of TeamInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamInfoRepository {
	mock := &TeamInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
