// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pull-request-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UsersRepository is an autogenerated mock type for the UsersRepository type
type UsersRepository struct {
	mock.Mock
}

type UsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersRepository) EXPECT() *UsersRepository_Expecter {
	return &UsersRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UsersRepository) GetUser(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UsersRepository_Expecter) GetUser(ctx interface{}, userID interface{}) *UsersRepository_GetUser_Call {
	return &UsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *UsersRepository_GetUser_Call) Run(run func(ctx context.Context, userID string)) *UsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UsersRepository_GetUser_Call) Return(_a0 *models.User, _a1 error) *UsersRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *UsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserActiveStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *UsersRepository) UpdateUserActiveStatus(ctx context.Context, userID string, isActive bool) error {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserActiveStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersRepository_UpdateUserActiveStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserActiveStatus'
type UsersRepository_UpdateUserActiveStatus_Call struct {
	*mock.Call
}

// UpdateUserActiveStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *UsersRepository_Expecter) UpdateUserActiveStatus(ctx interface{}, userID interface{}, isActive interface{}) *UsersRepository_UpdateUserActiveStatus_Call {
	return &UsersRepository_UpdateUserActiveStatus_Call{Call: _e.mock.On("UpdateUserActiveStatus", ctx, userID, isActive)}
}

func (_c *UsersRepository_UpdateUserActiveStatus_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *UsersRepository_UpdateUserActiveStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *UsersRepository_UpdateUserActiveStatus_Call) Return(_a0 error) *UsersRepository_UpdateUserActiveStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsersRepository_UpdateUserActiveStatus_Call) RunAndReturn(run func(context.Context, string, bool) error) *UsersRepository_UpdateUserActiveStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function with given fields: ctx, userID, username, teamName, isActive
func (_m *UsersRepository) UpsertUser(ctx context.Context, userID string, username string, teamName string, isActive bool) error {
	ret := _m.Called(ctx, userID, username, teamName, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) error); ok {
		r0 = rf(ctx, userID, username, teamName, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersRepository_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type UsersRepository_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - username string
//   - teamName string
//   - isActive bool
func (_e *UsersRepository_Expecter) UpsertUser(ctx interface{}, userID interface{}, username interface{}, teamName interface{}, isActive interface{}) *UsersRepository_UpsertUser_Call {
	return &UsersRepository_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, userID, username, teamName, isActive)}
}

func (_c *UsersRepository_UpsertUser_Call) Run(run func(ctx context.Context, userID string, username string, teamName string, isActive bool)) *UsersRepository_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *UsersRepository_UpsertUser_Call) Return(_a0 error) *UsersRepository_UpsertUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsersRepository_UpsertUser_Call) RunAndReturn(run func(context.Context, string, string, string, bool) error) *UsersRepository_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersRepository creates a new instance of UsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersRepository {
	mock := &UsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
