// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pull-request-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UserReviewRepository is an autogenerated mock type for the UserReviewRepository type
type UserReviewRepository struct {
	mock.Mock
}

type UserReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserReviewRepository) EXPECT() *UserReviewRepository_Expecter {
	return &UserReviewRepository_Expecter{mock: &_m.Mock}
}

// GetPRsByReviewer provides a mock function with given fields: ctx, userID
func (_m *UserReviewRepository) GetPRsByReviewer(ctx context.Context, userID string) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsByReviewer")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserReviewRepository_GetPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsByReviewer'
type UserReviewRepository_GetPRsByReviewer_Call struct {
	*mock.Call
}

// GetPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserReviewRepository_Expecter) GetPRsByReviewer(ctx interface{}, userID interface{}) *UserReviewRepository_GetPRsByReviewer_Call {
	return &UserReviewRepository_GetPRsByReviewer_Call{Call: _e.mock.On("GetPRsByReviewer", ctx, userID)}
}

func (_c *UserReviewRepository_GetPRsByReviewer_Call) Run(run func(ctx context.Context, userID string)) *UserReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserReviewRepository_GetPRsByReviewer_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *UserReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserReviewRepository_GetPRsByReviewer_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequestShort, error)) *UserReviewRepository_GetPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsStats provides a mock function with given fields: ctx
func (_m *UserReviewRepository) GetReviewsStats(ctx context.Context) ([]*models.ReviewerStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsStats")
	}

	var r0 []*models.ReviewerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.ReviewerStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ReviewerStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ReviewerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserReviewRepository_GetReviewsStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsStats'
type UserReviewRepository_GetReviewsStats_Call struct {
	*mock.Call
}

// GetReviewsStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserReviewRepository_Expecter) GetReviewsStats(ctx interface{}) *UserReviewRepository_GetReviewsStats_Call {
	return &UserReviewRepository_GetReviewsStats_Call{Call: _e.mock.On("GetReviewsStats", ctx)}
}

func (_c *UserReviewRepository_GetReviewsStats_Call) Run(run func(ctx context.Context)) *UserReviewRepository_GetReviewsStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserReviewRepository_GetReviewsStats_Call) Return(_a0 []*models.ReviewerStats, _a1 error) *UserReviewRepository_GetReviewsStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserReviewRepository_GetReviewsStats_Call) RunAndReturn(run func(context.Context) ([]*models.ReviewerStats, error)) *UserReviewRepository_GetReviewsStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserReviewRepository creates a new instance of UserReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserReviewRepository {
	mock := &UserReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
